// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/chunk_server_register.proto

package chunkserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkServerRegisterService_Register_FullMethodName = "/chunkserver.ChunkServerRegisterService/Register"
)

// ChunkServerRegisterServiceClient is the client API for ChunkServerRegisterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChunkServerRegisterServiceClient interface {
	Register(ctx context.Context, in *ChunkServerRegisterReq, opts ...grpc.CallOption) (*RegisterResp, error)
}

type chunkServerRegisterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkServerRegisterServiceClient(cc grpc.ClientConnInterface) ChunkServerRegisterServiceClient {
	return &chunkServerRegisterServiceClient{cc}
}

func (c *chunkServerRegisterServiceClient) Register(ctx context.Context, in *ChunkServerRegisterReq, opts ...grpc.CallOption) (*RegisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResp)
	err := c.cc.Invoke(ctx, ChunkServerRegisterService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChunkServerRegisterServiceServer is the server API for ChunkServerRegisterService service.
// All implementations must embed UnimplementedChunkServerRegisterServiceServer
// for forward compatibility.
type ChunkServerRegisterServiceServer interface {
	Register(context.Context, *ChunkServerRegisterReq) (*RegisterResp, error)
	mustEmbedUnimplementedChunkServerRegisterServiceServer()
}

// UnimplementedChunkServerRegisterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkServerRegisterServiceServer struct{}

func (UnimplementedChunkServerRegisterServiceServer) Register(context.Context, *ChunkServerRegisterReq) (*RegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedChunkServerRegisterServiceServer) mustEmbedUnimplementedChunkServerRegisterServiceServer() {
}
func (UnimplementedChunkServerRegisterServiceServer) testEmbeddedByValue() {}

// UnsafeChunkServerRegisterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkServerRegisterServiceServer will
// result in compilation errors.
type UnsafeChunkServerRegisterServiceServer interface {
	mustEmbedUnimplementedChunkServerRegisterServiceServer()
}

func RegisterChunkServerRegisterServiceServer(s grpc.ServiceRegistrar, srv ChunkServerRegisterServiceServer) {
	// If the following call pancis, it indicates UnimplementedChunkServerRegisterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkServerRegisterService_ServiceDesc, srv)
}

func _ChunkServerRegisterService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkServerRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkServerRegisterServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkServerRegisterService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkServerRegisterServiceServer).Register(ctx, req.(*ChunkServerRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChunkServerRegisterService_ServiceDesc is the grpc.ServiceDesc for ChunkServerRegisterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkServerRegisterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chunkserver.ChunkServerRegisterService",
	HandlerType: (*ChunkServerRegisterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ChunkServerRegisterService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/chunk_server_register.proto",
}
